[webservers]
web01 ansible_host=192.168.56.10 ansible_user=ubuntu server_role=webserver

[databases]
db01 ansible_host=192.168.56.11 ansible_user=ubuntu server_role=database

[lab:children]
webservers
databases
