---
- name: Restart apache
  ansible.builtin.service:
    name: "{{ apache_service_name }}"
    state: restarted

- name: Reload apache
  ansible.builtin.service:
    name: "{{ apache_service_name }}"
    state: reloaded
