---
galaxy_info:
  role_name: database
  author: jouw_naam
  description: Installeert MySQL en maakt dbuser/dbpassword aan voor de week 4 Ansible labopdracht.
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
dependencies:
  - name: community.mysql
