---
mysql_service_name: mysql
mysql_root_login_unix_socket: /var/run/mysqld/mysqld.sock
mysql_database_name: labdb
mysql_user_name: dbuser
mysql_user_password: dbpassword
mysql_allowed_host: "%"
mysql_packages:
  - mysql-server
  - python3-pymysql
